version: '3'
services:
  hello_world:
    build:
      context: .
      dockerfile: hello_world/Dockerfile
    environment:
      - INPUT='Test1, Test2'
    volumes:
      - bazel_cache_hello_world:/root/.cache/bazel
  grpc_server:
    build:
      context: .
      dockerfile: grpc_server/Dockerfile
    volumes:
      - bazel_cache_grpc_server:/root/.cache/bazel
    ports:
      - "4242:4242"
  grpc_client:
    build:
      context: .
      dockerfile: grpc_client/Dockerfile


volumes:
  bazel_cache_hello_world:
  bazel_cache_grpc_server:
