# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translator_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17translator_server.proto\x12\x14\x65xamples.grpc_server\"+\n\x15GetTranslationRequest\x12\x12\n\ninput_word\x18\x01 \x01(\t\"1\n\x16GetTranslationResponse\x12\x17\n\x0ftranslated_word\x18\x01 \x01(\t2{\n\nTranslator\x12m\n\x0eGetTranslation\x12+.examples.grpc_server.GetTranslationRequest\x1a,.examples.grpc_server.GetTranslationResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translator_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETTRANSLATIONREQUEST']._serialized_start=49
  _globals['_GETTRANSLATIONREQUEST']._serialized_end=92
  _globals['_GETTRANSLATIONRESPONSE']._serialized_start=94
  _globals['_GETTRANSLATIONRESPONSE']._serialized_end=143
  _globals['_TRANSLATOR']._serialized_start=145
  _globals['_TRANSLATOR']._serialized_end=268
# @@protoc_insertion_point(module_scope)
