# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import translator_server_pb2 as translator__server__pb2


class TranslatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTranslation = channel.unary_unary(
                '/examples.grpc_server.Translator/GetTranslation',
                request_serializer=translator__server__pb2.GetTranslationRequest.SerializeToString,
                response_deserializer=translator__server__pb2.GetTranslationResponse.FromString,
                )


class TranslatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTranslation(self, request, context):
        """Translates the given word.
        errors: no input word, no translation available
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTranslation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranslation,
                    request_deserializer=translator__server__pb2.GetTranslationRequest.FromString,
                    response_serializer=translator__server__pb2.GetTranslationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'examples.grpc_server.Translator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Translator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTranslation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/examples.grpc_server.Translator/GetTranslation',
            translator__server__pb2.GetTranslationRequest.SerializeToString,
            translator__server__pb2.GetTranslationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
